[package]
name = "rust-dapp"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.14", features = ["abigen"] }
tokio = { version = "1.38.0", features = ["full"] }
dotenv = "0.15"
log = "0.4.21"
env_logger = "0.11.3"
serde = { version = "1.0.203", features = ["derive"] }